name: mysql-app

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        networks:
            - mysql-app-network
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: /.env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 4000:4000
        networks:
            - mysql-app-network
        depends_on:
            - db

    redis-server:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - mysql-app-network

volumes:
    mysql_data:
networks:
    mysql-app-network:
        driver: bridge