export const MESSEGE_ERROR = "error"
export const MESSEGE_SUCCESS = "success"
export const MESSEGE_INTERNAL_SERVER_ERROR =  "Internal server error"
export const STATUS_OK = 200
export const STATUS_CREATED = 201
export const STATUS_PATCH = 200
export const STATUS_NO_CONTENT = 204
export const STATUS_INTERNAL_SERVER_ERROR = 500
export const STATUS_UNAUTHORIZED = 401
export const STATUS_BAD_REQUEST = 400
export const STATUS_FORBIDDEN = 403